### ISSUE TITLE
0.12.0 Published with incorrect license metadata

### ISSUE THREAD

**Issue by hjdivad** [15r10nk/inline-snapshot#104]
[pypi - 0.12.0](https://pypi.org/project/inline-snapshot/) does not show the license.
By contrast [pypi - 0.11.0](https://pypi.org/project/inline-snapshot/0.11.0/) correctly shows the license as MIT.

This issue breaks automatic license validation, which is useful for many businesses.

I'm not familiar enough with the details to know the exact issue and right course of action, but here's what I've dug up together with @rwjblue.

v0.11.0's `PKG-INFO` (built with `poetry build`) contains the following entries:

```text
Metadata-Version: 2.1
License: MIT
Classifier: License :: OSI Approved :: MIT License
```

Those lines are removed from v0.12.0's `PKG-INFO` (build with `hatch build`), which contains:

```text
Metadata-Version: 2.3
License-Expression: MIT
```

I don't know how pypi determines the license, but from what I can gather the `PKG-INFO` for 0.12.0 is invalid.

[PEP 639](https://peps.python.org/pep-0639/#add-license-expression-field) seems to do some things for metadata version 2.4
* Adds `License-Expression`
* Deprecates license classifiers

So the license fields in 0.12.0 seem to be targeting metadata 2.4 but `PKG-INFO` has metadata set to 2.3.

**Comment by 15r10nk** [comment]
This is probably related to this https://github.com/pypa/hatch/issues/665 ( because I used `hatch new` to generate a new project and used parts of the generated pyproject file)

I will verify this Monday. 
Thank you for the detailed issue.

**Comment by 15r10nk** [comment]
The license information is back in [0.12.1](https://pypi.org/project/inline-snapshot/0.12.1/). Thank you again for this report.
