### ISSUE TITLE
Non-interactive mode

### ISSUE THREAD

**Issue by pawamoy** [15r10nk/inline-snapshot#106]
I'm running tests with a task runner, which doesn't show any output until the task is finished and unless it failed (I'm generally not interested in the output of a task who passed).

Currently, if inline-snapshots prompts me for an answer, it looks like the task froze (eternally waiting). Could inline-snapshot add an option to say "yes always" when being prompted? In other words I'm requesting for a non-interactive mode :slightly_smiling_face:

**Comment by pawamoy** [comment]
Oh, I realize I used `review`, but could probably use `create` instead. Closing!

**Comment by 15r10nk** [comment]
--inline-snapshot=create,fix could also be useful for you, if you also want to fix existing snapshots.
