### ISSUE TITLE
Pytest integration examples are broken in the documentation

### ISSUE THREAD

**Issue by pederhan** [15r10nk/inline-snapshot#122]
All terminal output examples are broken on the [pytest integration page](https://15r10nk.github.io/inline-snapshot/pytest/) in the documentation.

<img width="686" alt="image" src="https://github.com/user-attachments/assets/0fef22e5-5372-4e0f-85df-554f3870e427">

They all fail with the error: `NameError: name 'dirty_equals' is not defined`

Just letting you know in case you are not aware. Thanks for making a great package! 😃

**Comment by pederhan** [comment]
I must have had an old cached version in my browser or something. This was clearly fixed in #119.

**Comment by 15r10nk** [comment]
No, I just fixed it and forgot to tell you before I went to lunch.

Thank you for letting me know about the broken documentation.
