### ISSUE TITLE
Please use "Pydantic Logfire" logo for sponsors

### ISSUE THREAD

**Issue by samuelcolvin** [15r10nk/inline-snapshot#124]
Thank you so much for showing our logo in the readme 🙏 

Please could you use this Pydantic Logfire logo as we're trying to promote [logfire](https://pydantic.dev/logfire) rather than the Pydantic library which everyone already knows about.

<img width="1719" alt="pydantic-logfire-lithium-tar" src="https://github.com/user-attachments/assets/78add290-06d4-4a86-b0ed-dd0c8cfeac01">

**Comment by 15r10nk** [comment]
I changed the logo and the link url.

and :pray: thank you for sponsoring me.

**Comment by samuelcolvin** [comment]
thanks so much.
