### ISSUE TITLE
Testing fails without `pytest-xdist`

### ISSUE THREAD

**Issue by mtelka** [15r10nk/inline-snapshot#126]
All three tests in `tests/test_xdist.py` fails when there is no `pytest-xdist` installed.  This is because `pytest-xdist` is not listed as a test dependency in the `pyproject.toml` file.

Here is an example of the failure:

```
__________________________________ test_xdist __________________________________

project = <tests.conftest.project.<locals>.Project object at 0x7fffac6a0400>

    def test_xdist(project):

        project.setup(
            """\

    def test_a():
        assert 1==snapshot()
    """ 
        )   

        result = project.run("--inline-snapshot=create", "-n=auto")
 
>       assert "\n".join(result.stderr.lines).strip() == snapshot(
            "ERROR: --inline-snapshot=create can not be combined with xdist"
        )
E       AssertionError: assert 'ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]\npytest: error: unrecognized arguments: -n=auto\n  inifile: None\n  rootdir: /tmp/pytest-of-marcel/pytest-7/test_xdist1' == 'ERROR: --inline-snapshot=create can not be combined with xdist'
E       
E         - ERROR: --inline-snapshot=create can not be combined with xdist
E         + ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
E         + pytest: error: unrecognized arguments: -n=auto
E         +   inifile: None
E         +   rootdir: /tmp/pytest-of-marcel/pytest-7/test_xdist1

/data/builds/oi-userland/components/python/inline-snapshot/build/amd64-3.9/tests/test_xdist.py:16: AssertionError
----------------------------- Captured stdout call -----------------------------
write code:
# äöß 🐍 
from inline_snapshot import snapshot
from inline_snapshot import outsource
  
  
  
def test_a():
    assert 1==snapshot()

running: pytest --inline-snapshot=create -n=auto
     in: /tmp/pytest-of-marcel/pytest-7/test_xdist1
----------------------------- Captured stderr call -----------------------------
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n=auto
  inifile: None
  rootdir: /tmp/pytest-of-marcel/pytest-7/test_xdist1
```

**Comment by 15r10nk** [comment]
Did you use `hatch test`?

**Comment by mtelka** [comment]
No.

We do not have support for `hatch test` in OpenIndiana, so for testing during packaging of `inline-snapshot` I use `pytest` with dependencies listed in `pyproject.toml` installed.

Is `pytest-xdist` an implicit dependency always satisfied by `hatch test`?

**Comment by 15r10nk** [comment]
> Is `pytest-xdist` an implicit dependency always satisfied by `hatch test`?

Yes, hatch test comes with several default dependencies https://hatch.pypa.io/latest/config/internal/testing/#dependencies

You can add pytest-xdist to your dependencies.

OpenIndiana is also interesting. Never heard about it.

**Comment by mtelka** [comment]
> > Is `pytest-xdist` an implicit dependency always satisfied by `hatch test`?
> 
> Yes, hatch test comes with several default dependencies https://hatch.pypa.io/latest/config/internal/testing/#dependencies

Thanks for the pointer!  Still, I'm not sure it is reliable to rely on some defaults that could easily change in future.

> You can add pytest-xdist to your dependencies.

Sure, I'm doing exactly that.

**Comment by mtelka** [comment]
FYI, the new `inline-snapshot` package is heading to OpenIndiana: https://github.com/OpenIndiana/oi-userland/pull/19452
