### ISSUE TITLE
Please replace `toml` dependency with `tomli`

### ISSUE THREAD

**Issue by mgorny** [15r10nk/inline-snapshot#130]
This package still requires `toml` for old Python versions. That library is unmaintained (last release in 2020), does not implement TOML correctly and has been removed from Linux distributions, making the dependency a blocker for packaging `inline-snapshot`. Could you please switch over to `tomli` instead? It's 100% compatible and interchangeable with the stdlib `tomllib`, so replacement should be trivial.

**Comment by 15r10nk** [comment]
Thank you for the info. I will fix it.

**Comment by 15r10nk** [comment]
fixed in 0.13.4

**Comment by mgorny** [comment]
Thank you.
