### ISSUE TITLE
time-machine test dependency is problematic for PyPy3

### ISSUE THREAD

**Issue by mgorny** [15r10nk/inline-snapshot#132]
I'm sorry to be bothering you but the `time-machine` test dependency that is present right now makes it impossible to run over 200 tests on PyPy3. `time-machine` relies on patching internals of CPython's `_datetime` implementation, and as such is not installable on PyPy3 at all.

Could you please consider using e.g. `pytest-freezer` instead? This one's portable and works across all Python implementations.

Unfortunately, PyPy3 support became important right now because `pydantic-core` started using `inline-snapshot`, and its consumers do support PyPy3.

**Comment by 15r10nk** [comment]
the time-machine problem is not so big. The PyPy3 support is a bigger problem. This could take a while.

**Comment by mgorny** [comment]
Oh, I've assumed that the lack of `time_machine` is the only problem. But from a quick patch, indeed I've seem to be still getting 192 failures.

If that's any help, my patch was:

```diff
diff --git a/tests/conftest.py b/tests/conftest.py
index 5ef37fc..8a69dc2 100644
--- a/tests/conftest.py
+++ b/tests/conftest.py
@@ -268,8 +268,8 @@ import datetime
 import pytest
 
 @pytest.fixture(autouse=True)
-def set_time(time_machine):
-        time_machine.move_to(datetime.datetime(2024, 3, 14, 0, 0, 0, 0),tick=False)
+def set_time(freezer):
+        freezer.move_to(datetime.datetime(2024, 3, 14, 0, 0, 0, 0))
         yield
 """
             )
```

**Comment by 15r10nk** [comment]
@mgorny could you please tell me if this fix would solve your issue for now?

I hope to provide support for pypy in the long term, but this might take a while.

**Comment by 15r10nk** [comment]
and I also know that I have a `"Programming Language :: Python :: Implementation :: PyPy"` classifier in my `pyproject.toml` ... I will fix this too.

**Comment by 15r10nk** [comment]
0.14.0 official supports pypy. But I removed the PYPY classifier because the code rewriting does not currently work.

**Comment by mgorny** [comment]
Thanks!
