### ISSUE TITLE
feat: Read configuration options in pytest config file (pytest.ini)

### ISSUE THREAD

**Issue by pawamoy** [15r10nk/inline-snapshot#164]
I generally avoid putting everything in pyproject.toml, and use one config file for each tool, stored in a `config` folder. Since I exclusively use inline-snapshot through pytest, it would feel intuitive to configure it in pytest's config file (in my case, `config/pytest.ini`)~~, just like how other pytest plugins can be configured there~~. Happy to try and send a PR, let me know :slightly_smiling_face:

**Comment by pawamoy** [comment]
Hmmm actually I'm not sure if pytest even allows configuring plugins in pytest.ini :thinking:

**Comment by pawamoy** [comment]
I opened https://github.com/pytest-dev/pytest/discussions/13078.

**Comment by pawamoy** [comment]
Alternatively, if reading ini is a no-go, I'd be happy with putting inline-snapshot config into its own config file:

```toml
# config/inline-snapshot.toml
snapshot-dir = "tests/snapshots"
```

```ini
[pytest]
addopts =
  --inline-snapshot-config config/inline-snapshot.toml
```

**Comment by 15r10nk** [comment]
I would prefer not to offer to many options to configure inline-snapshot. Does pyproject.toml in a parent folder work for you?

**Comment by pawamoy** [comment]
That's understandable. Yes it's only two lines (for now) so I'll tolerate it 😁 Let's close. Maybe we can reopen when inline-snapshot has lots of options 👍
