### ISSUE TITLE
more flexible reformatting options

### ISSUE THREAD

**Issue by brodybits** [15r10nk/inline-snapshot#51]
It may be helpful if I could disable Black reformatting. I will sometimes try to create & update snapshots, even with some other tests known to be failing. I would likely configure my snapshot updating task to run `black` then `ruff --fix` possibly with `--exit-zero` as well. But I would prefer to have my own control, if possible. I may want to use `ruff format` instead of `black` at some point in the future.

It may be nice to add a configuration that can configure to use one or multiple tools to do the reformatting, but not likely so important for me.

**Comment by 15r10nk** [comment]
inline-snapshot only formats your file after code changes if it was formatted with black before the code changes.

I don't understand why you could want to disable this formatting, because the file was already formatted with black by yourself.

**Comment by brodybits** [comment]
I thought I had issues with this, don't recall anything specific any longer. I think it would be ideal to document this super explicitly:

> inline-snapshot only formats your file after code changes if it was formatted with black before the code changes.

Thanks for the response & info.
