### ISSUE TITLE
New version without deprecated `--update-snapshots`

### ISSUE THREAD

**Issue by alexmojaki** [15r10nk/inline-snapshot#54]
I'm running into this error in CI:

```
argparse.ArgumentError: argument --update-snapshots: conflicting option string: --update-snapshots
```

I'm not passing this option or even using `inline-snapshot` at all in the relevant test, this conflict just happens while constructing the pytest argument parser while `inline-snapshot` is installed.

Since the argument is already deprecated, please can you release a new version in which it's removed?

**Comment by 15r10nk** [comment]
`--update-snapshots` is used by an other snapshot library (I don't exactly know which).
This was one reason why I changed the argument names in an early version of `inline-snapshot`.
The deprecated `--update-snapshots` option was just a reminder for people to switch to the new option.

I will remove it and release a new version.
