### ISSUE TITLE
Asserting length of lists

### ISSUE THREAD

**Issue by jxnl** [15r10nk/inline-snapshot#64]
is there any way to test length of lists like 

assert x = snapshot({"items": Length(4)})

or something, not sure how to describe this well, but sometimes i know its different entities but i know theres 4

**Comment by RazCrimson** [comment]
@jxnl 

You should be able to test it like this:

```
assert len(x["items"]) = snapshot(4)
```

**Comment by jxnl** [comment]
duh thanks!

**Comment by 15r10nk** [comment]
@RazCrimson, @jxnl: I like that you help each other :+1:

But there is also another solution:

```python
from inline_snapshot import snapshot
from dirty_equals import IsList


def test_something():
    assert {
        "data": [1, 2],
        "items": [1, 2, 3, 4],
    } == snapshot(
        {
            "data": [1, 2],
            "items": IsList(length=4),
        }
    )
```

You can replace parts of bigger data structures with dirty-equal expressions. inline-snapshot is still able to fix the parts which are not dirty-equal expressions when your values change.

https://15r10nk.github.io/inline-snapshot/eq_snapshot/#dirty-equals
