### ISSUE TITLE
Add Pandas integration (?)

### ISSUE THREAD

**Issue by lucianosrp** [15r10nk/inline-snapshot#67]
It would nice to have intragation for pandas' objects such as DataFrames. 
I have some data functions that I'd like to test; they fetch data from a SQL database and return a DataFrame. 

```python
def test_get_data():
    df = get_data()
    assert (df == snapshot()).all().all()
```
```python
def test_get_data():
    df = get_data()
    assert (df == snapshot(pd.DataFrame([{"col_a": 10, "col_b": 11}, {"col_a": 11, "col_b": 23 }]))).all().all()
```

Enabling custom objects in the library can create lots of overhead, so I am not sure if you are planning to add this at some point or if you would rather have "extensions"  something like `inline-snapshot-pandas` .

**Comment by 15r10nk** [comment]
I have no experience with pandas, but there might be some problems. 

inline-snapshot assumes that == has a `bool` return type. The `all()` in your code tells me that this is not the case. 

The other problem might be that DataFrames might be really big. Putting them into your code might not be a good idea in this case. One option might be to convert them into a csv and to use outsource().

I have currently no way to try things out, but one idea.

```
assert df_to_list(df) == snapshot([{"col_a": 10, "col_b": 11}, {"col_a": 11, "col_b": 23 }])
```

df_to_list should convert the data frame into a list of dicts. This would cause no problems with inline-snapshot and allow you to use dirty-equals for the values if you want.

creating a separate library with helper functions might be a good option. I don't know currently if it can be done without changes in inline-snapshot.

**Comment by lucianosrp** [comment]
> The other problem might be that DataFrames might be really big. Putting them into your code might not be a good idea in this case. 

I think this is a very valid point. It's not in my case currently but I can see how it could cause problems.

Your idea actually fits better and I guess is simpler than having to create a whole new feature just for a DataFrame!
