### ISSUE TITLE
Respecting max line length

### ISSUE THREAD

**Issue by Kobzol** [15r10nk/inline-snapshot#7]
Hi! I have to say that this library is quite awesome. I was searching for something like `insta` from Rust and found `pytest-insta`, but storing the diffs in separate files was overkill for my use-case. Then I found this package and it's exactly what I have wanted :)

I wanted to ask what do you think about configuring the max line length of stored snapshots. I'm using snapshots mostly for comparing long strings, and `inline-snapshot` usually generates something like `snapshot("<........ super long string>"`, and then `flake` gets angry because it gets over the max. line length. And since the snapshots are autogenerated, even if I fix it manually, after the next snapshot update I would have to re-wrap all the long snapshots again, which is annoying.

I resolved this by configuring `black` to auto-wrap these long lines for me, but I was wondering whether it could be useful to have this done automatically by `inline-snapshot`.

Anyway, thanks again for this great little package!

**Comment by 15r10nk** [comment]
It is great to hear that you like my package.

Inline-snapshot 0.2.0 already provides some features which should help you in your case.

- strings with newlines are converted into multiline strings with triple quotes (have you newlines in your strings?).
- the file is formatted with black if it was formatted before.

I guess that you have a problem because you configure black in some config file. Inline-snapshot ignores currently black config files. I will add support for black configuration files in the next release.

However, can you provide me a sample file with one of your long strings and your black configuration if you have any?
I would like to check if this would actually fix your problem.

**Comment by Kobzol** [comment]
So my string doesn't have a newline, that's probably why it wasn't formatted into multiple lines. I don't configure black with a config file, I'm just passing it parameters directly with CLI arguments (although I should probably switch to a config file). The configuration that I use is `black --preview -l 120` (`--preview` allows string wrapping).

The long string looked something like this:
```python
assert something == snapshot('worker start --idle-timeout "5m" --manager "<manager>" --server-dir "<server-dir>/001" --cpus "2x8" --resource "x=sum(100)" --resource "y=range(1-4)" --resource "z=[1,2,4]" --no-hyper-threading --no-detect-resources --on-server-lost "finish-running" --time-limit "1h"')
```

**Comment by 15r10nk** [comment]
0.2.1 is out, which respects black configuration files.

This means that you should configure black to use the preview flag in a configuration file.

pyproject.toml
``` toml
[tool.black]
preview = "True"
```

black can also be [configured globally](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#where-black-looks-for-the-file) if you want.

inline-snapshot should now see that your source code is already formatted with black and reformat the files after it changed the snapshots.

Please let me know if this works for you.

**Comment by Kobzol** [comment]
I configured black like this:
```
[tool.black]
line-length = 120
preview = true
```
with `pyproject.toml` in the root of my project. `black` now correctly respects this file.

I then updated to `inline-snapshot` `0.2.1` and tried to fix this snapshot:
```python
@all_managers
def test_pass_cpu_and_resources_to_worker(hq_env: HqEnv, spec: ManagerSpec):
    queue = ManagerQueue()
    manager = ExtractSubmitScriptPath(queue, spec.manager)

    with MockJobManager(hq_env, spec.adapt(manager)):
        hq_env.start_server()
        prepare_tasks(hq_env)

        add_queue(
            hq_env,
            manager=spec.manager_type(),
            additional_worker_args=[
                "--cpus",
                "2x8",
                "--resource",
                "x=sum(100)",
                "--resource",
                "y=range(1-4)",
                "--resource",
                "z=[1,2,4]",
                "--no-hyper-threading",
                "--no-detect-resources",
            ],
        )

        script = queue.get()
        assert normalize_output(hq_env, spec.manager_type(), " ".join(get_worker_args(script))) == snapshot(
            'workerx start --idle-timeout "5m" --manager "<manager>" --server-dir "<server-dir>/001" --cpus "2x8" --resource "x=sum(100)" --resource "y=range(1-4)" --resource "z=[1,2,4]" --no-hyper-threading --no-detect-resources --on-server-lost "finish-running" --time-limit "1h"'
        )
```

The string at the end is the long line. After running `python3 -m pytest --inline-snapshot=fix`, which should fix the beginning of that string from `workerx` to just `worker`, it generated this:
```python
assert normalize_output(hq_env, spec.manager_type(), " ".join(get_worker_args(script))) == snapshot('worker start --idle-timeout "5m" --manager "<manager>" --server-dir "<server-dir>/001" --cpus "2x8" --resource "x=sum(100)" --resource "y=range(1-4)" --resource "z=[1,2,4]" --no-hyper-threading --no-detect-resources --on-server-lost "finish-running" --time-limit "1h"')
```
(one very long line).

**Comment by Kobzol** [comment]
Ah, I see, I was trying to reproduce the original line-wrapping problem too much. Yup, I can confirm that if the file is preformatted, it now works and doesn't generate a long line. Thank you! :)
