### ISSUE TITLE
"N snapshots can be trimmed" but nothing is trimmed?

### ISSUE THREAD

**Issue by pawamoy** [15r10nk/inline-snapshot#78]
When I run my test suite, I get this output at the end:

```
=============== inline snapshot ====================
Info: 11 snapshots can be trimmed (--inline-snapshot=trim)
```

From the docs:

> trim removes every snapshots form the storage which is not referenced with external(...) in the code.

However if I run pytest with `--inline-snapshot=trim` it doesn't do anything. I have 11 external files indeed, so I suspect inline-snapshot doesn't detect `external` calls in my code:

```python
snapshots = snapshot(
    {
        (
            ("annotations_path", "brief"),
            ("separate_signature", True),
            ("show_signature", False),
            ("show_signature_annotations", False),
            ("signature_crossrefs", False),
            ("unwrap_annotated", True),
        ): external("3603a08e7614*.html"),
        ...
    }
)
```

**Comment by pawamoy** [comment]
Can't reproduce while debugging. `external` calls are correctly identified.

**Comment by 15r10nk** [comment]
0.9.0 contains now a check if you use xdist at the same time.

I think there are several issues with the current implementation of `outsource`. I have some ideas how the DX could be improved and wrote it down (#86). Please tell me if you have some feedback.

**Comment by pawamoy** [comment]
I think we can close this, since pytest-xdist is explicitly not supported. I tried again today and it works fine when xdist is not used.
