### ISSUE TITLE
Broken "pytest integration" documentation page

### ISSUE THREAD

**Issue by tmlmt** [15r10nk/inline-snapshot#98]
All python code blocks are failing in https://15r10nk.github.io/inline-snapshot/pytest/

Error messages:
- `environment: line 10: pytest: command not found`
- `/usr/local/bin/python: No module named pytest`

**Comment by 15r10nk** [comment]
Thank you for the report. I updated the documentation manually for now. An pipeline fix is on the way.

**Comment by 15r10nk** [comment]
the fix is part of #101
