### ISSUE TITLE
Add package to conda-forge

### ISSUE THREAD

**Issue by tmlmt** [15r10nk/inline-snapshot#99]
It'd be great to add the package to conda-forge (see [staging process](https://conda-forge.org/docs/maintainer/adding_pkgs/#creating-recipes)) so that it becomes available for installation with conda or (micro)mamba

**Comment by dhirschfeld** [comment]
***xref:***
  - https://github.com/conda-forge/staged-recipes/pull/27023

**Comment by 15r10nk** [comment]
@dhirschfeld do I have to do anything when I release a new version?

**Comment by dhirschfeld** [comment]
No, the `conda-forge` CI will automatically create a PR to the feedstock when a new version is published to PyPI and the maintainers of the feedstock will merge that.

If you'd like to be a maintainer on the feedstock you can open an issue in the feedstock with `@conda-forge-admin, please add user @15r10nk` in the title.

* https://conda-forge.org/docs/maintainer/infrastructure/#conda-forge-admin-please-add-user-username
* https://github.com/conda-forge/inline-snapshot-feedstock

**Comment by 15r10nk** [comment]
No is a great answer. I have currently enough to do do with my own libraries. Big thank you that you created the conda package :pray:

**Comment by dhirschfeld** [comment]
It wasn't me who added it, I just cross-referenced this issue to the PR!

**Comment by 15r10nk** [comment]
inline-snapshot is now in conda-forge https://anaconda.org/conda-forge/inline-snapshot

Thank you @wolfv
